AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

    goStructured:
        Type: AWS::Serverless::Function
        Properties:
           #Handler: goLambdaStructuredInAndOut.HandleLambdaEvent
           Handler: goLambdaStructuredInAndOut
           Runtime: go1.x
           CodeUri: s3://com.candywaydrive.go.builds/go-lambda-structured/goLambdaStructuredInAndOut.zip 

